language: python
matrix:
    include:
      - python: "2.7"
        env: TOX_SKIP_ENV=py3.*

      - python: "3.6"
        env: TOX_SKIP_ENV=py27.*,flake

install:
  - pip install tox
script:
  - tox
sudo: false
notifications:
    email: false
